### ISSUE TITLE
Port to WCOSS2 for GEFS

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GSDCHEM#1]
Based on WCOSS2 training material and wiki:

1. REMOVE –xHost , -xavx2 –xavx512 or any other –x flags as they may not work correctly!
2. Recommended Intel compiler flags to achieve best performance. This ives bit reproducible results from run to run with the same configuration.
- O3 -fp-model precise -ftz -fast-transcendentals -no-prec-div -no-prec-sqrt

**Comment by XianwuXue-NOAA** [comment]
@zhanglikate @lipan-NOAA Could you check my changes and let me know which branch I should request to do the PR? Thanks.

**Comment by zhanglikate** [comment]
@XianwuXue-NOAA  I have no idea about the WCOSS2 issue since I don't have the account. @lipan-NOAA may help you with, Thanks.

**Comment by XianwuXue-NOAA** [comment]
Thanks @zhanglikate

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA @zhanglikate 

  This changed has been suggested by WCOSS2 manual, therefore, I don't have any questions about this modification.

**Comment by XianwuXue-NOAA** [comment]
Thanks @lipan-NOAA Should I merge these changes to develop branch?

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA Is this change designated to WCOSS2 platform only ?

**Comment by XianwuXue-NOAA** [comment]
Good question. It will affect "intel" users, however, I don't know whether it will affect other users on other platforms

**Comment by XianwuXue-NOAA** [comment]
@lipan-NOAA Could you create a branch release/gefs_v12 based on commit id: 9e66aa1 for GEFS? Then I can merge my changes to this branch. So this will not affect others.

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA @rmontuoro I don't have authority for this repository. Raffaele is the owner of this repository.

**Comment by XianwuXue-NOAA** [comment]
@lipan-NOAA Thanks for let me know. @rmontuoro Could you create a branch release/gefs_v12 based on commit id: 9e66aa1 for GEFSv12? Thanks in advance.

**Comment by rmontuoro** [comment]
@XianwuXue-NOAA, @lipan-NOAA - I'm not the owner of this repository. Please contact @WalterKolczynski-NOAA.
Please also see my comment on your proposed code changes [here](https://github.com/XianwuXue-NOAA/GSDCHEM/commit/b2c9f13bb38612a85da00ff001483acf4713f0eb#commitcomment-59426524).

**Comment by WalterKolczynski-NOAA** [comment]
There isn't a need for a special branch for GEFS since this repo just serves GEFS (and future coupled, I guess). But if there is a need to have a shared branch for wcoss2, I can make a feature/wcoss2 branch.

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA Thanks. feature/wcoss2 is OK for me. I am not sure whether GFSv16 uses the same GSDCHEM or not. If it is, GFSv16 may also make some changes. Do you know what is charge of GSDCHEM?

**Comment by WalterKolczynski-NOAA** [comment]
GFS v16 doesn't use GSDCHEM at all.

Branch feature/wcoss2 created.
